Adds validator --minimal option to action
Materials-Consortia/optimade-validator-action pull request #60
Opened 2021-03-09 14:44 UTC by ml-evs

As it says on the tin.

No tests as its a simple argument (like skip optional), unless we really want them.

2021-03-09 15:45 UTC, CasperWA requested changes
I'd vote to up the minor version, so that's the change I've suggested.
Also because we're moving to `v1.0.1`.

Looks good otherwise.

As a note, I think we should try to test all options though, at least just one test to make sure it doesn't fail and passes the correct option to `optimade-validator`. You don't need to test the content.

2021-03-09 15:45 UTC, CasperWA commented on README.md
> +| `minimal` | Whether or not to reduce the validation to a minimal test set that only checks responses and not filters. | Optional | `false` | `v2.4.1+`
I'd just release a new minor version, honestly.
```suggestion
| `minimal` | Whether or not to reduce the validation to a minimal test set that only checks responses and not filters. | Optional | `false` | `v2.5+`
```

2021-03-09 16:47 UTC, CasperWA submitted a review, later dismissed
There. Now the tests are fine 😅 

You can leave me out of the authorship.

2021-03-09 17:48 UTC, ml-evs commented
> There. Now the tests are fine sweat_smile
> 
> You can leave me out of the authorship.

Huh, thanks, I guess `./run_tests.sh` locally doesn't run everything from the CI!

2021-03-09 17:59 UTC, merged

2021-03-10 12:43 UTC, CasperWA commented
> Huh, thanks, I guess `./run_tests.sh` locally doesn't run everything from the CI!

It should run all the BATS tests. Don't know what else you mean?